language: go

go:
  - 1.8
  - 1.9
  - "1.10"
  - 1.11

script:
  - make build
  - ./bin/tldr --update
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
